Supporting piped output

diff --git a/bin/ppb b/bin/ppb
--- a/bin/ppb
+++ b/bin/ppb
@@ -2,10 +2,11 @@
 
 . ~/.config/ppb.conf
 
+# Configuration variables check
 if [ -z ${PPB_TARGET_HOST+x} ]; then
 	echo "ERROR: The PPB_TARGET_HOST variable is unset."
 	echo "Nothing can be uploaded if there is no target host."
-	echo "Please copy the example config file from under \`/etc/ppb.conf\` to \`~/.config/ppb.conf\`,"
+	echo "Please copy the example config file from under \"/etc/ppb.conf\" to \"~/.config/ppb.conf\","
 	echo "and fill in the variable values according to your personal settings."
 	exit 1
 fi
@@ -14,19 +15,46 @@ if [ -z "$PPB_HTTP_PATH" ]; then
 	PPB_HTTP_PATH=${PPB_PATH_ON_HOST}
 fi
 
-FILEID=$(md5sum ${1})
-EXT="${1##*.}"
-FILEID="${FILEID:0:6}"
-if [[ "${1:0:1}" = "/" || "${1:0:1}" = "~" ]]; then
-	FILEPATH="${1}"
+# Differential handling of files and piped output
+if [ -z "${1}" ]; then
+	TMP_FILE=1
+	FILE_PATH="/var/tmp/ppb_$(date +%s).html"
+	ansifilter -H &> ${FILE_PATH}
+elif [[ ! -f ${1} ]]; then
+	echo "There is no \"${1}\" file to upload from your system."
+	exit 1
 else
-	FILEPATH="./${1}"
+	FILE_PATH=${1}
 fi
-if rsync -avP "${FILEPATH}" ${PPB_TARGET_HOST}:"${PPB_PATH_ON_HOST}/${FILEID}.${EXT}" ; then
+
+# Destination file path
+FILEID=$(md5sum ${FILE_PATH})
+EXT="${FILE_PATH##*.}"
+FILEID="${FILEID:0:6}"
+
+# Local file path fixing
+if [[ "${FILE_PATH:0:1}" = "/" || "${FILE_PATH:0:1}" = "~" ]]; then
+	FILE_PATH="${FILE_PATH}"
+else
+	FILE_PATH="./${FILE_PATH}"
+fi
+
+# Upload
+if rsync -avP "${FILE_PATH}" ${PPB_TARGET_HOST}:"${PPB_PATH_ON_HOST}/${FILEID}.${EXT}" ; then
 	echo Uploaded to: "https://${PPB_HTTP_PATH}/${FILEID}.${EXT}"
 else
 	echo ""
-	echo "ERROR: Could not upload, please check the command below:" &&
-	echo "rsync -avP \"${FILEPATH}\" ${PPB_TARGET_HOST}:\"${PPB_PATH_ON_HOST}/${FILEID}.${EXT}\"" &&
+	echo "ERROR: Could not upload, please check the command below:"
+	echo "rsync -avP \"${FILE_PATH}\" ${PPB_TARGET_HOST}:\"${PPB_PATH_ON_HOST}/${FILEID}.${EXT}\""
+	if [[ ${TMP_FILE} = 1 ]]; then
+		echo "The \"${FILE_PATH}\" file was created by PPB and intended as temporary."
+		echo "We leave it in place to aid in your debugging, please remember to delete it."
+	fi
 	exit 1
+fi
+
+# Cleanup
+if [[ ${TMP_FILE} = 1 ]]; then
+	echo ${FILE_PATH}
+	rm ${FILE_PATH}
 fi
