Tab not whitespace

diff --git a/bin/ppb b/bin/ppb
--- a/bin/ppb
+++ b/bin/ppb
@@ -3,28 +3,28 @@
 . ~/.config/ppb.conf
 
 USAGE="Usage: $(basename $0) [ -n -h ] <path>\n
-        -d:     Print debugging output.\n
-        -n:     Do not write output to clipboard (wl-clipboard and xclip).\n
-        -h:     Displays help message.\n
-        <path>:	Path to pastebin to be formatted.\n
+	-d:	Print debugging output.\n
+	-n:	Do not write output to clipboard (wl-clipboard and xclip).\n
+	-h:	Displays help message.\n
+	<path>:	Path to pastebin to be formatted.\n
 "
 
 # Read options:
 while getopts "nh" flag
 do
-        case "$flag" in
-                n)
-                        NO_CLIPBOARD=1
-                        ;;
-                h)
-                        echo -e "$USAGE"
-                        exit 0
-                        ;;
-                \?)
-                        echo "Invalid option: -$OPTARG" >&2
-                        exit 1
-                        ;;
-        esac
+	case "$flag" in
+		n)
+			NO_CLIPBOARD=1
+			;;
+		h)
+			echo -e "$USAGE"
+			exit 0
+			;;
+		\?)
+			echo "Invalid option: -$OPTARG" >&2
+			exit 1
+			;;
+	esac
 done
 
 # Configuration variables check
diff --git a/bin/rppb b/bin/rppb
--- a/bin/rppb
+++ b/bin/rppb
@@ -1,27 +1,27 @@
 #! /bin/bash
 
 USAGE="Usage: $(basename $0) [ -n -h ] <target>\n
-        -n:     Do not write output to clipboard (wl-clipboard and xclip).\n
-        -h:     Displays help message.\n
-        <target>:  String to be formatted.\n
+	-n:     	Do not write output to clipboard (wl-clipboard and xclip).\n
+	-h:     	Displays help message.\n
+	<target>:	String to be formatted.\n
 "
 
 # Read options:
 while getopts "nh" flag
 do
-        case "$flag" in
-                n)
-                        NO_CLIPBOARD=1
-                        ;;
-                h)
-                        echo -e "$USAGE"
-                        exit 0
-                        ;;
-                \?)
-                        echo "Invalid option: -$OPTARG" >&2
-                        exit 1
-                        ;;
-        esac
+	case "$flag" in
+		n)
+			NO_CLIPBOARD=1
+			;;
+		h)
+			echo -e "$USAGE"
+			exit 0
+			;;
+		\?)
+			echo "Invalid option: -$OPTARG" >&2
+			exit 1
+			;;
+	esac
 done
 
 TARGET=${@:$OPTIND}
