Help text and clipboard options

diff --git a/bin/ppb b/bin/ppb
--- a/bin/ppb
+++ b/bin/ppb
@@ -2,6 +2,31 @@
 
 . ~/.config/ppb.conf
 
+USAGE="Usage: $(basename $0) [ -d -l -n -u -h ] <path>\n
+        -d:     Print debugging output.\n
+        -n:     Do not write output to clipboard (wl-clipboard and xclip).\n
+        -h:     Displays help message.\n
+        <path>:	Path to pastebin to be formatted.\n
+"
+
+# Read options:
+while getopts "dlnuh" flag
+do
+        case "$flag" in
+                n)
+                        NO_CLIPBOARD=1
+                        ;;
+                h)
+                        echo -e "$USAGE"
+                        exit 0
+                        ;;
+                \?)
+                        echo "Invalid option: -$OPTARG" >&2
+                        exit 1
+                        ;;
+        esac
+done
+
 # Configuration variables check
 if [ -z ${PPB_TARGET_HOST+x} ]; then
 	echo "ERROR: The PPB_TARGET_HOST variable is unset."
@@ -42,8 +67,16 @@ fi
 
 # Upload
 if rsync --chmod=644 -avPL "${FILE_PATH}" ${PPB_TARGET_HOST}:"${PPB_PATH_ON_HOST}/${DEST_FILE}" &> /dev/null ; then
-	echo "Uploaded to:"
-	echo "https://${PPB_HTTP_PATH}/${DEST_FILE}"
+	URL="https://${PPB_HTTP_PATH}/${DEST_FILE}"
+	if [ -z "$NO_CLIPBOARD" ]; then
+		wl-copy "${URL}"
+		echo "${URL}" | xclip
+		echo "Upload succeeded and URL added to clioboard:"
+		echo "${URL}"
+	else
+		echo "Uploaded to:"
+		echo "${URL}"
+	fi
 else
 	echo ""
 	echo "ERROR: Could not upload, please check the command below:"
